drop database bookstore;
create database bookstore;
use bookstore;
source  bookstore_scripts/01_mysql_create.sql
source  bookstore_scripts/02_mysql_populate_author.sql
source  bookstore_scripts/03_mysql_populate_publisher.sql
source  bookstore_scripts/04_mysql_populate_lookups.sql
source  bookstore_scripts/05_mysql_populate_book.sql
source  bookstore_scripts/06_mysql_populate_bookauthor.sql
source  bookstore_scripts/07_mysql_populate_country.sql
source  bookstore_scripts/08_mysql_populate_address.sql
source  bookstore_scripts/09_mysql_populate_customer.sql
source  bookstore_scripts/10_mysql_populate_others.sql
source  bookstore_scripts/11_mysql_populate_order.sql
source  bookstore_scripts/12_mysql_populate_orderline.sql
source  bookstore_scripts/13_mysql_populate_orderhistory.sql
